let suggestions = [
    "Accounting",
    "Advanced Library Research",
    "Africana Studies",
    "Anthropology",
    "Anthropology Honors College",
    "Arabic",
    "Art",
    "Art History",
    "Arts & Sciences",
    "Atmospheric Science",
    "Biology",
    "Biology Honors College",
    "Biomedical Sciences",
    "Biometry & Statistics",
    "Business",
    "Business Law",
    "Chemistry",
    "Chemistry Honors College",
    "Chinese",
    "Classics-Latin",
    "Communication",
    "Communication Honors College",
    "Computer Science",
    "Counseling Psychology",
    "Criminal Justice",
    "Cyber Security",
    "Documentary Studies",
    "East Asian Studies",
    "East Asian Studies Honors Coll",
    "Economics",
    "Economics Honors College",
    "Educational Psychology",
    "Educational Theory & Practice",
    "Educationl Policy & Leadership",
    "Electrical & Computr Engineering",
    "Emerg Mgmt & Homeland Security",
    "EmergPrep,HomeSec & Cyb Hon Coll",
    "EmergPrep,HomelandSec & CyberSec",
    "English",
    "English Honors College",
    "Environ & Sustainbl Engineering",
    "Environmental Health Sciences",
    "Environmental Sciences",
    "Epidemiology",
    "Finance",
    "French",
    "Freshman Seminar Program",
    "Geography",
    "German",
    "Globalization Studies",
    "Health Policy & Management",
    "Hebrew",
    "History 1",
    "History 2",
    "History Honors College",
    "Info Security & Digital Forenscs",
    "Info Systems & Bus Analytics",
    "Informatics",
    "Information Science",
    "Intensive English Language",
    "Intensive English Language Pgm",
    "Interdisc. Studies Honors Coll",
    "Interdisciplinary Studies",
    "International Affairs",
    "Italian",
    "Japanese",
    "Journalism",
    "Journalism Honors College",
    "Judaic Studies",
    "Korean",
    "Latin Amer & Carib Honors Coll",
    "Latin American & Caribbean Std",
    "Liberal Studies",
    "Linguistics",
    "Literacy Teaching & Learning",
    "Management",
    "Marketing",
    "Mathematics",
    "Mathematics Honors College",
    "Medieval & Renaissance Studies",
    "Music",
    "Music Honors College",
    "Nanoscale Sciences & Engineering",
    "Philosophy",
    "Philosophy Honors College",
    "Philosophy of Education",
    "Physics",
    "Physics Honors College",
    "Planning",
    "Political Science",
    "Political Science Honors Coll",
    "Portuguese",
    "Psychology",
    "Psychology Honors College",
    "Public Administration",
    "Public Affairs",
    "Public Health",
    "Religious Studies",
    "Russian",
    "School Psychology",
    "Social Welfare",
    "Sociology",
    "Sociology Honors College",
    "Spanish",
    "Special Education",
    "Study Abroad",
    "Theatre",
    "Urban Studies & Planning",
    "Women's,Gender & Sexuality St",
    "XAdirondack CC",
    "XAlbany College of Pharmacy",
    "XAlbany Law School",
    "XAlbany Medical College",
    "XAlfred State",
    "XBinghamton University",
    "XBrockport",
    "XBroome CC",
    "XBuffalo State",
    "XCanton",
    "XCayuga Community College",
    "XClinton Community College",
    "XCollege of St. Rose",
    "XColumbia-Greene CC",
    "XCorning Community College",
    "XCortland",
    "XDelhi",
    "XDownstate Medical Center",
    "XDutchess Community College",
    "XEmpire State College",
    "XEnvironmental Sci & Forestry",
    "XErie Community College",
    "XFarmingdale State College",
    "XFashion Institute of Tech",
    "XFinger Lakes CC",
    "XFredonia",
    "XFulton Montgomery CC",
    "XGenesee Community College",
    "XGeneseo",
    "XHerkimer County CC",
    "XHudson Valley CC",
    "XJamestown Community College",
    "XJefferson Community College",
    "XMaria College",
    "XMaritime College",
    "XMohawk Community College",
    "XMonroe Community College",
    "XMorrisville State",
    "XNassau Community College",
    "XNew Paltz",
    "XNiagaria County CC",
    "XNorth Country CC",
    "XOld Westbury",
    "XOneonta",
    "XOnondaga Community College",
    "XOptometry",
    "XOrange County CC",
    "XOswego",
    "XPlattsburgh",
    "XPotsdam",
    "XPurchase",
    "XRPI",
    "XRockland Community College",
    "XSUNYIT",
    "XSchenectady County CC",
    "XSiena College",
    "XSkidmore College",
    "XSouthern VT College",
    "XStony Brook University",
    "XSuffolk County CC",
    "XSullivan County CC",
    "XSuny Cobleskill",
    "XThe Sage Colleges",
    "XTompkins Cortland CC",
    "XUlster County CC",
    "XUnion College",
    "XUniversity at Buffalo",
    "XUpstate Medical University",
    "XWestchester Community College",
];

